### ISSUE TITLE
[Task #32] Update project documentation on Overleaf

### ISSUE THREAD

**Issue by Laronk** [AGH-Narzedzia-Informatyczne/meshi#32]
Update the Meshi project documentation main file on the Overleaf platform.

## Acceptance Criteria:
 *  Following components are added to the documentation:
    - [x] new main project image:
      - resource [delicious-ramen-soup-background.zip](https://github.com/AGH-Narzedzia-Informatyczne/meshi/files/5536342/delicious-ramen-soup-background.zip)
      - already cropped image: [meshi_team_profile_picture](https://user-images.githubusercontent.com/38437109/99066082-b36e0f00-25a8-11eb-8b8c-0435b595e61f.jpg)
    - [x] the new image author must be given recognition for his work (some form of attribution)
    - [x] document authors (full name and email) are added
    - [x] project short description
- [x] used technologies are presented as a table with technology: name, description, version, licence
- [x] title is emphasised with grater font size and text stylization

**Comment by YgLK** [comment]
Overleaf updated properly.
