### ISSUE TITLE
[Task #36] Add gists section to README

### ISSUE THREAD

**Issue by Aleksander2a** [AGH-Narzedzia-Informatyczne/meshi#41]
Create a section in README to contain links to gists of each developer. 

## Acceptance Criteria:
- [ ] each line in the file corresponds to a single developer
- [ ] there are no duplicate lines
- [ ] each developer has to add his gists to the list
- [ ] everyone must provide at least 2 gists
* Following people are added to the contributors list (GitHub usernames)
  - [x] Laronk
  - [X] Aleksander2a
  - [x] YgLK
  - [x] danielhenel
  - [x] piotrekg35

**Comment by Laronk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Task #36] Add gists section to README](https://trello.com/c/NfTO0Coc/48-task-36-add-gists-section-to-readme)
