### ISSUE TITLE
[Task #57] Documentation

### ISSUE THREAD

**Issue by Aleksander2a** [AGH-Narzedzia-Informatyczne/meshi#58]
Wykorzystując dowolny tryb edycji proszę przygotować minimum 4. strony dokumentacji Państwa projektu (poza tą, która już jest). Proszę wykorzystać różne elementy formatowania. Chciałbym, żeby znalazły się tam poniższe informacje

## Acceptance Criteria:
- [x] jakie jest przeznaczenie rozwiązania (jaki problem rozwiązuje? jaka jest motywacja?)
- [x] czym się Państwo inspirowaliście
- [x] użyte technologie
- [x] jak używać tego, co Państwo napisaliście (co jest wymagane, co trzeba wpisać, co pobrać, itp.)
- [x] jak działa aplikacja
- [x] omówienie interfejsu graficznego (jeśli jest obecny)
- [x] co się udało/co się nie udało
- [x] jakie są plany na przyszłość (co można udoskonalić)

Dla chętnych:
- [ ] można przygotować i wygenerować dokumentację kodu

**Comment by danielhenel** [comment]
@Aleksander2a Can I ask you for a review? There can be a lot of grammatical errors, because my English is not the best :)

**Comment by Aleksander2a** [comment]
> @Aleksander2a Can I ask you for a review? There can be a lot of grammatical errors, because my English is not the best :)

In 'Room for improvement" I just changed "was" to "were" in this sentence: "The Figma tools were(was) used for this.". Everything else seems fine
